name: Magisk
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Copy hosts to magisk dir
      run: cp releases/hosts dev/magisk/
    - name: Zip magisk dir
      run: |
        cd dev/magisk
        zip -r bebasid-magisk.zip *
        ls -l
    - name: Move bebasid-magisk to releases
      run: |
        mv dev/magisk/bebasid-magisk.zip releases/
        cd releases
        ls -l
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v10.1
    - name: Validating hosts changes, run next command if it is true
      if: contains(steps.changed-files.outputs.modified_files, 'releases/hosts')
      run: |
          echo "hosts file has been modified."
          LAST_COMMIT_MESSAGE="$(git log -1 --pretty="%s %b")"
          git config --global user.email "gvoze32@yahoo.com"
          git config --global user.name "zksbot"
          cd releases
          ls -l
          git add bebasid-magisk.zip
          git commit -m "Magisk sync: ${LAST_COMMIT_MESSAGE}"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.UPDATE_TOKEN }}
